In [2]:
import rmnn as rm
import collections
import numpy as np

parameters = collections.OrderedDict()
parameters['siren_1']=[2,256,1,4]
parameters['splitsiren_1']=[2,256,[10,10],4,'tucker']
#net='mulsiren',parameters=[2,256,[10,10],4,'tucker']
net = rm.represent.get_nn(net='composition',parameters=parameters)
data = np.random.random((2,3))
mask = np.zeros((2,3))
mask[0,2] = 1
data_train_loader,data_val_loader,data_test_loader = rm.toolbox.get_dataloader(x_mode='inr',batch_size=128,shuffle_if=False,data=data,mask=mask,xrange=1)

#print(net.G)

In [1]:
import rmnn as rm
img_arr = rm.toolbox.load_data('./data/img/Cameraman.jpg',data_type='rgb_img',data_shape=None)
import matplotlib.pyplot as plt
plt.imshow(img_arr)
plt.show()


rm.toolbox.save_data(data_path='./data/img/test.jpg',data_type='img',data=img_arr)

<Figure size 640x480 with 1 Axes>

In [26]:
import rmnn as rm
mask = rm.toolbox.load_mask(mask_type='random',random_rate=0.5,mask_path=None,data_shape=(5,2,3),mask_shape='same')
print(mask.shape)
print(mask)

a = ['dsd']
isinstance(a,list)

(5, 2, 3)
[[[0. 0. 1.]
  [0. 1. 0.]]

 [[0. 1. 0.]
  [1. 1. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 1.]
  [0. 1. 0.]]

 [[1. 1. 1.]
  [1. 0. 0.]]]


True

In [28]:
def g(*args):
    print(*args,'g')

def f(*args):
    print(*args)
    g(*args)

f('test')

test
test g
